artifacts_root: artifacts

#Data Ingestion config yaml file
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/kafu77/DataSets_repo/raw/main/chicken_disease.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

 